// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OpcUaClient.DataAccessLayer;

#nullable disable

namespace OpcUaClient.DataAccessLayer.Migrations
{
    [DbContext(typeof(ServiceDbContext))]
    [Migration("20250403060704_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OpcUaClient.Domain.Models.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<int>("Address")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ConvertBeforeRecalcForRead")
                        .HasColumnType("boolean");

                    b.Property<bool>("ConvertBeforeRecalcForWrite")
                        .HasColumnType("boolean");

                    b.Property<float>("Factor")
                        .HasColumnType("real");

                    b.Property<bool>("HasWriteRegister")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Offset")
                        .HasColumnType("real");

                    b.Property<int>("OutputType")
                        .HasColumnType("integer");

                    b.Property<bool>("Recalc")
                        .HasColumnType("boolean");

                    b.Property<byte>("RoundingAccuracy")
                        .HasColumnType("smallint");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<bool>("UseOutputType")
                        .HasColumnType("boolean");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WriteRegisterAddress")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Tag", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
